language: python
python:
- '3.5'
install:
- pip install -r requirements.txt
- pip install pytest
script: py.test
deploy:
  provider: pypi
  user: abhsag
  password:
    secure:
      imP+h4sKtNiovM/1XJ0cSU+RquRaD+XY7TJj+rU96TnE/1HRrx2jR1cTmEoGGwzbg1/KxqeBU+1McuBbMWXER4f5cI+4RU8+eP5Dev0pA4BPD113UUtKCKlNDhv2C0cVYUunNerLlno+JCg31OmOJXBoMbHPugj2u5KSggaunM5u0Lavwv0XcpMaVIvIEi5hPFZYgYyN1lNIl+kn1hdh9lkzJrbCIJBDoADfmDF+cs2JOhsV1KTgaS30EaU+1PlybOgqRREu1Niw7FXu7gsCxBBdE05+9vf0AFM6JaulcvZHVHZNHGoRum6lFWzYQRMs9hlP3jZB5nltTeAvRlnr9KaOHQNRxaQbuVpE0bXa+7fq0Ha9JcNLUl6EYhncoomsOqpEhkwzDksE08GqPBH9RTcxHyr2YaKKBSfojpjiOxXZc844D08129LJ5hF0Ta3pzTWr4tN1JCusAx8BR875NEvaqfFBT4IyGz/ReBmT/49T6KT0TY+dUFu/78hJCGNfClmnmGwHllhjppbwtRhQ8Y8DIrcYMxNuAhsPit4VKx7hKyxq0gJsH2fJVEAy9YQy7Yjoq3dTxkDC4Z6IQrgB8docARehR6qq2QsJgYEXPOuWn6/m+ScEexchdtMbzI2rvQMv/7LAyA0YiHsrefYvl/FQUg2RI9+Uqs9m23pxukc=
  on:
    branch: production
